NAME = fvigotti/utils-apacheutils
VERSION = latest

# sample : https://github.com/phusion/baseimage-docker/blob/master/Makefile
.PHONY: all build

all: build

build:
	docker build -t $(NAME):$(VERSION) src