NAME = fvigotti/webserver-nginx-consultpl
VERSION = 0.1

# sample : https://github.com/phusion/baseimage-docker/blob/master/Makefile
.PHONY: all build

all: build

build:
	docker build -t $(NAME):$(VERSION) src