?><?php
$i = 1;
$cfg['Servers'][$i]['host'] = 'mysqlA';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'pp';
$cfg['Servers'][$i]['auth_type'] = 'config';

//
//$cfg['Servers'][$i]['socket'] = '';
//$cfg['Servers'][$i]['ssl'] = false;
//$cfg['Servers'][$i]['ssl_key'] = null;
//$cfg['Servers'][$i]['ssl_cert'] = null;
//$cfg['Servers'][$i]['ssl_ca'] = null;
//$cfg['Servers'][$i]['ssl_ca_path'] = null;
//$cfg['Servers'][$i]['ssl_ciphers'] = null;
//$cfg['Servers'][$i]['connect_type'] = 'tcp';
//$cfg['Servers'][$i]['compress'] = false;
//$cfg['Servers'][$i]['controlhost'] = '';
//$cfg['Servers'][$i]['controlport'] = '';
//$cfg['Servers'][$i]['controluser'] = '';
//$cfg['Servers'][$i]['controlpass'] = '';
//$cfg['Servers'][$i]['auth_http_realm'] = '';
//$cfg['Servers'][$i]['auth_swekey_config'] = '';
//$cfg['Servers'][$i]['SignonSession'] = '';
//$cfg['Servers'][$i]['SignonScript'] = '';
//$cfg['Servers'][$i]['SignonURL'] = '';
//$cfg['Servers'][$i]['LogoutURL'] = '';
//$cfg['Servers'][$i]['nopassword'] = false;
//$cfg['Servers'][$i]['only_db'] = '';
//$cfg['Servers'][$i]['hide_db'] = '';
//$cfg['Servers'][$i]['verbose'] = '';
//$cfg['Servers'][$i]['pmadb'] = '';
//$cfg['Servers'][$i]['bookmarktable'] = '';
//$cfg['Servers'][$i]['relation'] = '';
//$cfg['Servers'][$i]['table_info'] = '';
//$cfg['Servers'][$i]['table_coords'] = '';
//$cfg['Servers'][$i]['pdf_pages'] = '';
//$cfg['Servers'][$i]['column_info'] = '';
//$cfg['Servers'][$i]['history'] = '';
//$cfg['Servers'][$i]['recent'] = '';
//$cfg['Servers'][$i]['favorite'] = '';
//$cfg['Servers'][$i]['table_uiprefs'] = '';
//$cfg['Servers'][$i]['tracking'] = '';
//$cfg['Servers'][$i]['userconfig'] = '';
//$cfg['Servers'][$i]['users'] = '';
//$cfg['Servers'][$i]['usergroups'] = '';
//$cfg['Servers'][$i]['navigationhiding'] = '';
//$cfg['Servers'][$i]['savedsearches'] = '';
//$cfg['Servers'][$i]['central_columns'] = '';
//$cfg['Servers'][$i]['designer_settings'] = '';
//$cfg['Servers'][$i]['export_templates'] = '';
//$cfg['Servers'][$i]['MaxTableUiprefs'] = 100;
//$cfg['Servers'][$i]['SessionTimeZone'] = '';
//$cfg['Servers'][$i]['AllowRoot'] = true;
//$cfg['Servers'][$i]['AllowNoPassword'] = false;
//$cfg['Servers'][$i]['AllowDeny']['order'] = '';
//$cfg['Servers'][$i]['AllowDeny']['rules'] = array();
//$cfg['Servers'][$i]['DisableIS'] = false;
//$cfg['Servers'][$i]['tracking_version_auto_create'] = false;
//$cfg['Servers'][$i]['tracking_default_statements'];
//$cfg['Servers'][$i]['tracking_add_drop_view'] = true;
//$cfg['Servers'][$i]['tracking_add_drop_table'] = true;
//$cfg['Servers'][$i]['tracking_add_drop_database'] = true;

// $i++;
$i++;
$cfg['Servers'][$i]['host'] = 'mysqlB';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'p2';
$cfg['Servers'][$i]['auth_type'] = 'config';
//
//$i++;
//$cfg['Servers'][$i]['host'] = 'mysqlA';
//$cfg['Servers'][$i]['port'] = '3306';
//$cfg['Servers'][$i]['user'] = 'root';
//$cfg['Servers'][$i]['password'] = 'pp';
//$cfg['Servers'][$i]['auth_type'] = 'config';
