FROM fvigotti/env-fatubuntu


RUN pip install --upgrade pip && \
    pip install  python-swiftclient python-keystoneclient

# pip install  libffi-dev libssl-dev     pyopenssl ndg-httpsclient pyasn1  && \
